### ISSUE TITLE
[Request] Grouping Sub folders into Parent Folder

### ISSUE THREAD

**Issue by matt873** [anilbeesetti/nextplayer#290]
Please add an option in quick settings for grouping subfolders into parent folders for a minimal number of folders on the homepage.

**Comment by anilbeesetti** [comment]
Unfortunately, the requested functionality cannot be achieved due to the current permissions being requested by the next player. To enable this feature, full storage permission would need to be granted, but this comes at the expense of privacy. Therefore, implementing this feature is not feasible.

Note: Please refrain from comparing MX Player and Next Player, as Next Player operates with limited permissions.

**Comment by matt873** [comment]
Can you add this feature as optional in settings like some apps have done? Here I will mention YTDLnis. They have added optional permission in settings for managing all directories. This way it will not comprise privacy and will add flexibility. Why I am insisting because grouping subfolders in parent folders makes things organised and tidy and clean. Your choice but just my suggestion if you consider it.

P.S. Toggling on this feature in quick settings would lead to permission asking for managing all directories by the app.

![Screenshot_20230529-215150_1.png](https://github.com/anilbeesetti/nextplayer/assets/108935493/a9bb77c0-9406-4655-87b4-fe006eaddc22)

**Comment by matt873** [comment]
Can you add this feature as optional in settings like some apps have done? Here I will mention YTDLnis. They have added optional permission in settings for managing all directories. This way it will not comprise privacy and will add flexibility. Why I am insisting because grouping subfolders in parent folders makes things organised and tidy and clean. Your choice but just my suggestion if you consider it.

P.S. Toggling on this feature in quick settings would lead to permission asking for managing all directories by the app.

![Screenshot_20230529-215150_1.png](https://github.com/anilbeesetti/nextplayer/assets/108935493/a9bb77c0-9406-4655-87b4-fe006eaddc22)

    @anilbeesetti

**Comment by matt873** [comment]
Can you add this feature as optional in settings like some apps have done? Here I will mention YTDLnis. They have added optional permission in settings for managing all directories. This way it will not comprise privacy and will add flexibility. Why I am insisting because grouping subfolders in parent folders makes things organised and tidy and clean. Your choice but just my suggestion if you consider it.

P.S. Toggling on this feature in quick settings would lead to permission asking for managing all directories by the app.

![Screenshot_20230529-215150_1.png](https://github.com/anilbeesetti/nextplayer/assets/108935493/a9bb77c0-9406-4655-87b4-fe006eaddc22)

    @anilbeesetti Your thoughts on this?

**Comment by anilbeesetti** [comment]
That's a good idea, and I appreciate your suggestion. I will take some time to consider it. However, please note that I have some other tasks to work on before addressing this. Therefore, I am reopening this matter for now. Thank you for your understanding.

**Comment by asifahmad134** [comment]
Please Please add this option because of this option not available in next player , I am forced to use mx player. Please note that with storages like 128GB/256GB as common nowadays, grouping subfolders in parent folders makes things organized and tidy and clean.
i love that feature on the other audio players like AIMP and musicolet
