### ISSUE TITLE
Redesigned App Icon :P

### ISSUE THREAD

**Issue by XelXen** [anilbeesetti/nextplayer#372]
![Frame 653](https://github.com/anilbeesetti/nextplayer/assets/78258352/503c5794-d93a-4169-8384-86a30b2fb374)
![Frame 655](https://github.com/anilbeesetti/nextplayer/assets/78258352/dd6a03b7-c046-4796-9308-068444df1e76)

**Comment by XelXen** [comment]
[icon.zip](https://github.com/anilbeesetti/nextplayer/files/11784876/icon.zip)
Uploaded in a zip since GitHub compresses images

**Comment by anilbeesetti** [comment]
Hello, @XelXen. I wanted to express my gratitude for your efforts. The icon you created is excellent, although it doesn't quite align with my vision. I was hoping for a simpler color scheme, preferably solid colors instead of neon shades. Additionally, I would appreciate it if the icon could incorporate a play symbol to indicate that the app functions as a video player. Thank you!

**Comment by XelXen** [comment]
Hmm alright, I'll try that too

**Comment by Turhvjbufv** [comment]
Honestly a shame it won't be implemented, looks nice

**Comment by anilbeesetti** [comment]
> Honestly a shame it won't be implemented, looks nice

I understand, the icon has a visually appealing design. However, incorporating it into app splash theme might present challenges. I'll try my best to use the icon
