### ISSUE TITLE
[BUG] Sometimes screen rotation doesnt work.

### ISSUE THREAD

**Issue by sinaaj** [anilbeesetti/nextplayer#729]
https://github.com/anilbeesetti/nextplayer/assets/76717433/5b6fee59-ec0f-4d9a-a3b8-71c4c37ab8d4

**Comment by anilbeesetti** [comment]
@sinaaj I've observed this on my phone while using Lineage OS. Since no one has reported this issue so far, I initially suspected it might be a problem related to Lineage OS. The problem arises when tapping the screen rotation button, as it activates navigation gestures due to the button's lower placement. I can attempt to resolve this by relocating the rotation button to the top of the screen.

**Comment by sinaaj** [comment]
Actually i have reported it long time ago
https://github.com/anilbeesetti/nextplayer/issues/451#issue-1813814584
I was too lazy at that moment to open another issue. I really dont mind where the button gonna be, i just want it to work
